# Generated by Django 4.2.3 on 2023-08-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('mail_contact', models.EmailField(max_length=254)),
                ('site', models.URLField()),
                ('code_client', models.CharField(blank=True, max_length=100)),
                ('mot_de_passe', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(default='fournisseurs/usine.png', upload_to='fournisseurs/')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
