# Generated by Django 4.2.3 on 2023-08-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0002_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='adresse',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='ville',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='mail_contact',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='mot_de_passe',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='code_postal',
            new_name='postal',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='code_client',
            new_name='user_code',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='pays',
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(default='suppliers/usine.png', upload_to='suppliers/'),
        ),
    ]
