# Generated by Django 4.2.3 on 2023-08-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0005_supplier_is_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
