# Generated by Django 4.2.3 on 2023-08-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0006_alter_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
