# Generated by Django 4.2.3 on 2023-08-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0007_alter_supplier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfunction',
            name='logo',
            field=models.ImageField(default='users/user.png', upload_to='users/'),
        ),
    ]
