# Generated by Django 4.2.3 on 2023-08-16 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0008_userfunction_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['last_name']},
        ),
    ]
