# Generated by Django 4.2.3 on 2023-08-27 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0011_alter_customuser_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='function',
            field=models.ForeignKey(default=9, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PPH.userfunction'),
        ),
    ]
