# Generated by Django 4.2.3 on 2023-12-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0016_alter_matierepremiere_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matierepremiere',
            name='fournisseur',
            field=models.CharField(max_length=200),
        ),
    ]
