# Generated by Django 4.2.3 on 2023-12-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0018_alter_matierepremiere_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='typematiere',
            name='logo',
            field=models.ImageField(default='matieres/actif.png', upload_to='matieres/'),
        ),
    ]
