# Generated by Django 4.2.3 on 2023-12-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0019_typematiere_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typematiere',
            name='logo',
            field=models.ImageField(default='matieres/actif.jpg', upload_to='matieres/'),
        ),
    ]
