# Generated by Django 4.2.3 on 2023-12-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0021_alter_matierepremiere_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='forme',
            name='qté_mesure',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
