# Generated by Django 4.2.3 on 2023-12-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0022_forme_qté_mesure'),
    ]

    operations = [
        migrations.AddField(
            model_name='matierepremiere',
            name='qté_cdt',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
