# Generated by Django 4.2.3 on 2023-12-14 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0023_matierepremiere_qté_cdt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forme',
            old_name='qté_mesure',
            new_name='unite_stock',
        ),
    ]
