# Generated by Django 4.2.3 on 2023-12-15 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0026_typeprep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matierepremiere',
            options={'ordering': ['nom']},
        ),
    ]
