# Generated by Django 4.2.3 on 2023-12-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0027_alter_matierepremiere_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PPH.typeprep')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qté', models.CharField(max_length=200)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPH.matierepremiere')),
                ('num_formule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPH.formules')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPH.forme')),
            ],
        ),
    ]
