# Generated by Django 4.2.3 on 2023-12-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0028_formules_composition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formules',
            new_name='Formule',
        ),
    ]
