# Generated by Django 4.2.3 on 2023-12-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0032_parametresprep'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresprep',
            name='unite',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
