# Generated by Django 4.2.3 on 2024-01-01 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0033_parametresprep_unite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresFormules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_formule', models.CharField(max_length=200)),
                ('parametre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPH.parametresprep')),
            ],
        ),
    ]
