# Generated by Django 4.2.3 on 2024-01-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0035_formule_agiter_formule_contre_indications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formule',
            name='contre_indications',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='formule',
            name='duree',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='formule',
            name='mode_operatoire',
            field=models.CharField(max_length=1000),
        ),
    ]
