# Generated by Django 4.2.3 on 2024-01-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0037_alter_composition_num_formule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='num_formule',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='composition',
            name='qté',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
