# Generated by Django 4.2.3 on 2024-01-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0038_alter_composition_num_formule_alter_composition_qté'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PPH.matierepremiere'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='unite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PPH.forme'),
        ),
    ]
