# Generated by Django 4.2.3 on 2024-01-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0039_alter_composition_matiere_alter_composition_unite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='unite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PPH.unitemesure'),
        ),
    ]
