# Generated by Django 4.2.3 on 2024-01-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0040_alter_composition_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='matierepremiere',
            name='attente_livraison',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matierepremiere',
            name='cde_auto',
            field=models.BooleanField(default=False),
        ),
    ]
