# Generated by Django 4.2.3 on 2024-01-10 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0041_matierepremiere_attente_livraison_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qté', models.CharField(max_length=200, null=True)),
                ('prep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PPH.formule')),
            ],
        ),
    ]
