# Generated by Django 4.2.3 on 2024-01-10 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0043_fiches'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandes',
            name='date_prevu',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
