# Generated by Django 4.2.3 on 2024-01-10 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0044_demandes_date_prevu'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiches',
            name='date_prevu',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
