# Generated by Django 4.2.3 on 2024-01-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0045_fiches_date_prevu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiches',
            old_name='date_prevu',
            new_name='date_fab',
        ),
    ]
