# Generated by Django 4.2.3 on 2024-01-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0046_rename_date_prevu_fiches_date_fab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fiches',
            name='service',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
