# Generated by Django 4.2.3 on 2024-01-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0047_service_fiches_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiches',
            name='qté',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
