# Generated by Django 4.2.3 on 2024-01-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0048_fiches_qté'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandes',
            name='commentaire',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
