# Generated by Django 4.2.3 on 2024-01-17 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0050_alter_demandes_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandes',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PPH.service'),
        ),
    ]
