# Generated by Django 4.2.3 on 2024-01-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0051_demandes_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='calcul',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
