# Generated by Django 4.2.3 on 2024-01-21 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0052_composition_calcul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forme',
            name='unite_mesure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formes_mesure', to='PPH.unitemesure'),
        ),
        migrations.AlterField(
            model_name='forme',
            name='unite_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formes_stock', to='PPH.unitemesure'),
        ),
    ]
