# Generated by Django 4.2.3 on 2024-01-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0053_alter_forme_unite_mesure_alter_forme_unite_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
    ]
