# Generated by Django 4.2.3 on 2024-01-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0055_matierepremiere_cdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matierepremiere',
            name='qté_cdt',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='matierepremiere',
            name='qté_stock',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
