# Generated by Django 4.2.3 on 2024-01-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0056_alter_matierepremiere_qté_cdt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matierepremiere',
            name='qté_stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
