# Generated by Django 4.2.3 on 2024-01-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0057_alter_matierepremiere_qté_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='cdt',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
