# Generated by Django 4.2.3 on 2024-01-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0058_catalogue_cdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='prix_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
