# Generated by Django 4.2.3 on 2024-01-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0059_catalogue_prix_catalogue_prix_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='prix_unit',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
