# Generated by Django 4.2.3 on 2024-01-26 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0060_alter_catalogue_prix_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='cmr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='forme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PPH.forme'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PPH.typematiere'),
        ),
        migrations.AddField(
            model_name='matierepremiere',
            name='cmr',
            field=models.BooleanField(default=False),
        ),
    ]
