# Generated by Django 4.2.3 on 2024-01-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0061_catalogue_cmr_catalogue_forme_catalogue_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='froid',
            field=models.BooleanField(default=False),
        ),
    ]
