# Generated by Django 4.2.3 on 2024-01-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0062_catalogue_froid'),
    ]

    operations = [
        migrations.AddField(
            model_name='matierepremiere',
            name='froid',
            field=models.BooleanField(default=False),
        ),
    ]
