# Generated by Django 4.2.3 on 2024-01-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0063_matierepremiere_froid'),
    ]

    operations = [
        migrations.AddField(
            model_name='matierepremiere',
            name='code_fournisseur',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matierepremiere',
            name='ean',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
