# Generated by Django 4.2.3 on 2024-01-27 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0064_matierepremiere_code_fournisseur_matierepremiere_ean'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPH.supplier')),
            ],
        ),
    ]
