# Generated by Django 4.2.3 on 2024-01-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0066_remove_typematiere_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriematiere',
            options={'ordering': ['nom']},
        ),
        migrations.AddField(
            model_name='supplier',
            name='download_catalogue',
            field=models.BooleanField(default=False),
        ),
    ]
