# Generated by Django 4.2.3 on 2024-01-27 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0067_alter_categoriematiere_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='imports/')),
                ('page_debut', models.IntegerField(max_length=200)),
                ('page_fin', models.IntegerField(max_length=200)),
                ('code_debut', models.CharField(max_length=200)),
                ('code_fin', models.CharField(max_length=200)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPH.categoriematiere')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPH.supplier')),
            ],
            options={
                'ordering': ['date_import'],
            },
        ),
    ]
