# Generated by Django 4.2.3 on 2024-01-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0068_catalogueimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueimport',
            name='page_debut',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='catalogueimport',
            name='page_fin',
            field=models.IntegerField(),
        ),
    ]
