# Generated by Django 4.2.3 on 2024-01-28 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0069_alter_catalogueimport_page_debut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogue',
            name='cdt',
        ),
        migrations.RemoveField(
            model_name='catalogue',
            name='forme',
        ),
        migrations.AddField(
            model_name='catalogue',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PPH.categoriematiere'),
        ),
    ]
