# Generated by Django 4.2.3 on 2024-01-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0072_alter_matierepremiere_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matierepremiere',
            name='prix_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
