# Generated by Django 4.2.3 on 2024-01-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0073_alter_matierepremiere_prix_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matierepremiere',
            name='nom',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
