# Generated by Django 4.2.3 on 2024-01-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0074_alter_matierepremiere_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='matierepremiere',
            name='unite_cdt',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
