# Generated by Django 4.2.3 on 2024-01-30 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0075_matierepremiere_unite_cdt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matierepremiere',
            options={},
        ),
    ]
