# Generated by Django 4.2.3 on 2024-02-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0076_alter_matierepremiere_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueimport',
            name='data_source',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
