# Generated by Django 4.2.3 on 2024-02-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0077_catalogueimport_data_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogue',
            name='prix_unit',
        ),
    ]
