# Generated by Django 4.2.3 on 2024-02-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0079_reception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matierepremiere',
            name='qté_stock',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reception',
            name='certificat',
            field=models.FileField(null=True, upload_to='certificats/'),
        ),
    ]
