# Generated by Django 4.2.3 on 2024-02-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0081_reception_stock_reception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='stock_reception',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
