# Generated by Django 4.2.3 on 2024-02-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0082_alter_reception_stock_reception'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_long', models.CharField(max_length=100, unique=True)),
                ('nom_court', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('postal', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('site', models.URLField(blank=True)),
                ('logo', models.ImageField(default='hopitaux/defaut.jpg', upload_to='hopitaux/')),
            ],
            options={
                'ordering': ['nom_long'],
            },
        ),
    ]
