# Generated by Django 4.2.3 on 2024-02-14 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0083_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiches',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiches',
            name='controle_valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fiches',
            name='controleur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches_controleur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiches',
            name='patient',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fiches',
            name='preparateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches_preparateur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiches',
            name='typePrep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PPH.typeprep'),
        ),
        migrations.AddField(
            model_name='parametresformules',
            name='valeur_parametre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
