# Generated by Django 4.2.3 on 2024-02-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0084_fiches_age_fiches_controle_valide_fiches_controleur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formule',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formule',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
