# Generated by Django 4.2.3 on 2024-02-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0085_formule_is_activate_formule_is_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresTarifs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_horaire_preparateur', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tarif_horaire_pharmacien', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='formule',
            name='prix_ht',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='formule',
            name='prix_ttc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='formule',
            name='temps_controle',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='formule',
            name='temps_preparation',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='matierepremiere',
            name='prix_ttc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='matierepremiere',
            name='prix_unit_ttc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='matierepremiere',
            name='tva',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
