# Generated by Django 4.2.3 on 2024-02-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0086_parametrestarifs_formule_prix_ht_formule_prix_ttc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matierepremiere',
            options={'ordering': ['nom']},
        ),
    ]
