# Generated by Django 4.2.3 on 2024-02-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0087_alter_matierepremiere_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiches',
            name='destruction',
            field=models.BooleanField(default=False),
        ),
    ]
