# Generated by Django 4.2.3 on 2024-02-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0088_fiches_destruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandes',
            name='prescripteur',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='demandes',
            name='production',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fiches',
            name='prescripteur',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
