# Generated by Django 4.2.3 on 2024-02-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0089_demandes_prescripteur_demandes_production_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametresformules',
            name='num_formule',
            field=models.IntegerField(max_length=200),
        ),
    ]
