# Generated by Django 4.2.3 on 2024-02-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0090_alter_parametresformules_num_formule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametresformules',
            name='num_formule',
            field=models.IntegerField(),
        ),
    ]
