# Generated by Django 4.2.3 on 2024-02-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0091_alter_parametresformules_num_formule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='num_formule',
            field=models.IntegerField(null=True),
        ),
    ]
