# Generated by Django 4.2.3 on 2024-02-16 22:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0093_remove_parametresformules_valeur_parametre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandes',
            old_name='qté',
            new_name='patient',
        ),
        migrations.AddField(
            model_name='demandes',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='demandes',
            name='date_demande',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='demandes',
            name='typePrep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PPH.typeprep'),
        ),
    ]
