# Generated by Django 4.2.3 on 2024-02-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0094_rename_qté_demandes_patient_demandes_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='qté',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
