# Generated by Django 4.2.3 on 2024-02-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0095_alter_composition_qté'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='resettable',
            field=models.BooleanField(default=True),
        ),
    ]
