# Generated by Django 4.2.3 on 2024-02-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0096_catalogue_resettable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matierepremiere',
            name='prix_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='matierepremiere',
            name='prix_unit_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
