# Generated by Django 4.2.3 on 2024-02-19 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0097_alter_matierepremiere_prix_ttc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueimport',
            name='resettable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='composition',
            name='resettable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fiches',
            name='resettable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formule',
            name='resettable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matierepremiere',
            name='resettable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametresdemandes',
            name='resettable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametresformules',
            name='resettable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametrestarifs',
            name='tarif_controle',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='resettable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='resettable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fiches',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PPH.service'),
        ),
    ]
