# Generated by Django 4.2.3 on 2024-02-19 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0098_catalogueimport_resettable_composition_resettable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiches',
            name='qté',
        ),
        migrations.AddField(
            model_name='demandes',
            name='recurence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fiches',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fiches',
            name='attente_controle',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ParametresFiches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_fiche', models.IntegerField()),
                ('valeur_parametre', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('resettable', models.BooleanField(default=True)),
                ('parametre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPH.parametresprep')),
            ],
        ),
    ]
