# Generated by Django 4.2.3 on 2024-02-19 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0099_remove_fiches_qté_demandes_recurence_fiches_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiches',
            name='public',
        ),
        migrations.AddField(
            model_name='formule',
            name='controleur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formules_controleur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formule',
            name='créateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formules_createur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formule',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
