# Generated by Django 4.2.3 on 2024-02-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0101_rename_public_formule_cloud_fiches_qté'),
    ]

    operations = [
        migrations.AddField(
            model_name='formule',
            name='pediatric',
            field=models.BooleanField(default=False),
        ),
    ]
