# Generated by Django 4.2.3 on 2024-02-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0102_formule_pediatric'),
    ]

    operations = [
        migrations.AddField(
            model_name='formule',
            name='specialite',
            field=models.BooleanField(default=False),
        ),
    ]
