# Generated by Django 4.2.3 on 2024-02-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0103_formule_specialite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='unite',
        ),
    ]
