# Generated by Django 4.2.3 on 2024-02-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0104_remove_composition_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandes',
            name='delai',
            field=models.IntegerField(null=True),
        ),
    ]
