# Generated by Django 4.2.3 on 2024-02-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0105_demandes_delai'),
    ]

    operations = [
        migrations.AddField(
            model_name='formule',
            name='hospitaliere',
            field=models.BooleanField(default=False),
        ),
    ]
