# Generated by Django 4.2.3 on 2024-02-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0106_formule_hospitaliere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandes',
            name='delai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandes',
            name='recurence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
