# Generated by Django 4.2.3 on 2024-02-20 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0107_alter_demandes_delai_alter_demandes_recurence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['modele'],
            },
        ),
        migrations.CreateModel(
            name='FabricantsBalances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('postal', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site', models.URLField(blank=True)),
                ('user_code', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('is_activate', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstructionsBalances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('nom_instruction', models.CharField(max_length=100, unique=True)),
                ('valeur_instruction', models.TextField(blank=True, null=True)),
                ('reponse_instruction', models.TextField(blank=True, null=True)),
                ('modele_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPH.balances')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='balances',
            name='fabricant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPH.fabricantsbalances'),
        ),
    ]
