# Generated by Django 4.2.3 on 2024-02-21 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0108_balances_fabricantsbalances_instructionsbalances_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EpiFormules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_formule', models.IntegerField()),
                ('resettable', models.BooleanField(default=True)),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPH.epi')),
            ],
        ),
    ]
