# Generated by Django 4.2.3 on 2024-02-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0109_epi_epiformules'),
    ]

    operations = [
        migrations.AddField(
            model_name='matierepremiere',
            name='densite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
