# Generated by Django 4.2.3 on 2024-02-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0114_rename_nom_instruction_instructionsbalances_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionsbalances',
            name='reponse',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
