# Generated by Django 4.2.3 on 2024-02-21 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0115_instructionsbalances_reponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructionsbalances',
            old_name='reponse',
            new_name='format_reponse',
        ),
    ]
