# Generated by Django 4.2.3 on 2024-02-22 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0116_rename_reponse_instructionsbalances_format_reponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='matierepremiere',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PPH.categoriematiere'),
        ),
    ]
