# Generated by Django 4.2.3 on 2024-02-22 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0117_matierepremiere_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesFormules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_formule', models.IntegerField()),
                ('resettable', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PPH.matierepremiere')),
            ],
        ),
    ]
