# Generated by Django 5.0.2 on 2024-03-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0119_parametresformules_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='echantillon',
            field=models.BooleanField(default=True),
        ),
    ]
