# Generated by Django 5.0.2 on 2024-03-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0122_reception_qte_echantillon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='stock_reception',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
