# Generated by Django 5.0.2 on 2024-03-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0124_balances_duree_calibration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balances',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
    ]
