# Generated by Django 5.0.2 on 2024-03-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0125_balances_is_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='balances',
            name='prochaine',
            field=models.DateField(blank=True, null=True),
        ),
    ]
